name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: /home/runner/.cache/yarn/v6
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
